# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: HotPin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build -c Release HotPin.netcore.sln
    - name: Publish
      run: dotnet publish --configuration Release --self-contained false --framework net6.0-windows --runtime win-x64 HotPin.netcore.sln
    - name: Generate Artifact Name
      id: generate-name
      run: |
        echo "::set-output name=artifact::${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}.zip"
    - name: Generate Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.generate-name.outputs.artifact }}
        path: ./HotPin/bin/Release/net6.0-windows/win-x64/publish

