# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      id: build
      run: dotnet build -c Release HotPin.netcore.sln
    - name: Publish
      id: publish
      run: dotnet publish --output "output" --configuration Release --self-contained false --runtime win-x64 HotPin.netcore.sln
    - name: Artifact Name
      id: artifac-name
      run: |
        echo "::set-output name=artifact::${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}.zip"
    - name: Tag Name
      id: tag-name
      run: |
        echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
    - name: Copy HotPin.exe
      run: cp HotPin.exe ./output/HotPin.exe
    - name: Generate Artifact
      id: generate-artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.artifac-name.outputs.artifact }}
        path: ./output
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: "HotPin v${{ steps.tag-name.outputs.tag }}"
        tag_name: ${{ steps.tag-name.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Release Artifact
      id: upload_release_artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./output
        asset_name: "HotPin v${{ steps.tag-name.outputs.tag }}.zip"
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ github.token }}
